name: wireless_pov_poi_app
description: "Multi-platform Flutter app for Wireless POV Poi control via BLE"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_blue_plus: ^1.35.5
  rxdart: ^0.28.0
  image: ^4.0.17
  path: ^1.8.2
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  tuple: ^2.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - patterns/
